cp ./core_ssim.py ./script/ssim_XYUH-002.py
cp ./core_ssim.py ./script/ssim_XYUH-007.py
cp ./core_ssim.py ./script/ssim_vSYYZ178.py
cp ./core_ssim.py ./script/ssim_vSYYZ216.py
cp ./core_ssim.py ./script/ssim_vSYYZ385.py
cp ./core_ssim.py ./script/ssim_vSYYZ426.py
cp ./core_ssim.py ./script/ssim_vSYYZ51.py
cp ./core_ssim.py ./script/ssim_xfsy_0004.py
cp ./core_ssim.py ./script/ssim_xfsy_0109.py
cp ./core_ssim.py ./script/ssim_xfsy_0115.py
cp ./core_ssim.py ./script/ssim_xfsy_0121.py
cp ./core_ssim.py ./script/ssim_xfsy_0153.py
cp ./core_ssim.py ./script/ssim_xfsy_0154.py
cp ./core_ssim.py ./script/ssim_xfsy_0158.py
cp ./core_ssim.py ./script/ssim_xfsy_0161.py
cp ./core_ssim.py ./script/ssim_xfsy_0168.py
cp ./core_ssim.py ./script/ssim_xfsy_0170.py
cp ./core_ssim.py ./script/ssim_xfsy_0171.py
cp ./core_ssim.py ./script/ssim_xfsy_0172.py
cp ./core_ssim.py ./script/ssim_xfsy_0176.py
cp ./core_ssim.py ./script/ssim_xfsy_0186.py
cp ./core_ssim.py ./script/ssim_xfsy_0189.py
cp ./core_ssim.py ./script/ssim_xfsy_0193.py
cp ./core_ssim.py ./script/ssim_xfsy_0194.py
cp ./core_ssim.py ./script/ssim_xfsy_0197.py
cp ./core_ssim.py ./script/ssim_xfsy_0202.py
cp ./core_ssim.py ./script/ssim_xfsy_0203.py
cp ./core_ssim.py ./script/ssim_xfsy_0205.py
cp ./core_ssim.py ./script/ssim_xfsy_0208.py
cp ./core_ssim.py ./script/ssim_xfsy_0221.py
cp ./core_ssim.py ./script/ssim_xfsy_0225.py
cp ./core_ssim.py ./script/ssim_xfsy_0227.py
cp ./core_ssim.py ./script/ssim_xfsy_0233.py
cp ./core_ssim.py ./script/ssim_xfsy_0242.py
cp ./core_ssim.py ./script/ssim_xfsy_0248.py
cp ./core_ssim.py ./script/ssim_xfsy_0251.py
cp ./core_ssim.py ./script/ssim_xfsy_0253.py
cp ./core_ssim.py ./script/ssim_xfsy_0258.py
cp ./core_ssim.py ./script/ssim_xfsy_0266.py
cp ./core_ssim.py ./script/ssim_xfsy_0269.py
cp ./core_ssim.py ./script/ssim_xfsy_0283.py
cp ./core_ssim.py ./script/ssim_xfsy_0288.py
cp ./core_ssim.py ./script/ssim_xfsy_0291.py
cp ./core_ssim.py ./script/ssim_xfsy_0299.py
cp ./core_ssim.py ./script/ssim_xfsy_0301.py
cp ./core_ssim.py ./script/ssim_xfsy_0306.py
cp ./core_ssim.py ./script/ssim_xfsy_0320.py
cp ./core_ssim.py ./script/ssim_xfsy_0321.py
cp ./core_ssim.py ./script/ssim_xfsy_0324.py
cp ./core_ssim.py ./script/ssim_xfsy_0326.py
cp ./core_ssim.py ./script/ssim_xfsy_0336.py
cp ./core_ssim.py ./script/ssim_xfsy_0340.py
cp ./core_ssim.py ./script/ssim_xfsy_0352.py
cp ./core_ssim.py ./script/ssim_xfsy_0361.py
cp ./core_ssim.py ./script/ssim_xfsy_0367.py
cp ./core_ssim.py ./script/ssim_xfsy_0369.py
cp ./core_ssim.py ./script/ssim_xfsy_0371.py
cp ./core_ssim.py ./script/ssim_xfsy_0377.py
cp ./core_ssim.py ./script/ssim_xfsy_0382.py
cp ./core_ssim.py ./script/ssim_xfsy_0383.py
cp ./core_ssim.py ./script/ssim_xfsy_0384.py
cp ./core_ssim.py ./script/ssim_xfsy_0385.py
cp ./core_ssim.py ./script/ssim_xfsy_0386.py
cp ./core_ssim.py ./script/ssim_xfsy_0387.py
cp ./core_ssim.py ./script/ssim_xfsy_0399.py
cp ./core_ssim.py ./script/ssim_xfsy_0401.py
cp ./core_ssim.py ./script/ssim_xfsy_0402.py
cp ./core_ssim.py ./script/ssim_xfsy_0403.py
cp ./core_ssim.py ./script/ssim_xfsy_0404.py
cp ./core_ssim.py ./script/ssim_xfsy_0405.py
cp ./core_ssim.py ./script/ssim_xfsy_0406.py
cp ./core_ssim.py ./script/ssim_xfsy_0407.py
cp ./core_ssim.py ./script/ssim_xfsy_0409.py
cp ./core_ssim.py ./script/ssim_xfsy_0411.py
cp ./core_ssim.py ./script/ssim_xfsy_0413.py
cp ./core_ssim.py ./script/ssim_xfsy_0423.py
cp ./core_ssim.py ./script/ssim_xfsy_0429.py
cp ./core_ssim.py ./script/ssim_xfsy_0431.py
cp ./core_ssim.py ./script/ssim_xfsy_0436.py
cp ./core_ssim.py ./script/ssim_xfsy_0441.py
cp ./core_ssim.py ./script/ssim_xfsy_0442.py
cp ./core_ssim.py ./script/ssim_xfsy_0443.py
cp ./core_ssim.py ./script/ssim_xfsy_0447.py
cp ./core_ssim.py ./script/ssim_xfsy_0450.py
cp ./core_ssim.py ./script/ssim_xfsy_0452.py
cp ./core_ssim.py ./script/ssim_xfsy_0456.py
cp ./core_ssim.py ./script/ssim_xfsy_0465.py
cp ./core_ssim.py ./script/ssim_xfsy_0476.py
cp ./core_ssim.py ./script/ssim_xfsy_0480.py
cp ./core_ssim.py ./script/ssim_xfsy_0487.py
cp ./core_ssim.py ./script/ssim_xfsy_0505.py
cp ./core_ssim.py ./script/ssim_xfsy_0506.py
cp ./core_ssim.py ./script/ssim_xfsy_0507.py
cp ./core_ssim.py ./script/ssim_xfsy_0512.py
cp ./core_ssim.py ./script/ssim_xfsy_0520.py
cp ./core_ssim.py ./script/ssim_xfsy_0521.py
cp ./core_ssim.py ./script/ssim_xfsy_0522.py